In [5]:
import numpy as np

 1. What is a Python library? Why do we use Python libraries?

 2. What is the difference between Numpy array and List?

In [ ]:
Difference between Numpy array and Python List are given below

                Numpy Array                                    |                      Python List
1.It doesnot  store additional information about each element. | 1.Lists in Python store additional information about each element.
                                                               |
2.It cannot hold different data types.                         | 2.Lists can hold different data types.
                                                               | 
3.Itt store elements in contiguous memory locations.           | 3.Lists may not store elements in contiguous memory locations.
                                                               | 
4.Numpy array is more optimized for numerical computationss.   | 4.Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. 
                                                               |
5.Numpy array has extra metadata as shape,strides,and data type| 5. It doesnot have extra metadata. 
                                                               |
    
                                                                
                                                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                            
                                                                

In [6]:
arr1= np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [7]:
np.size(arr1)

12

In [8]:
np.ndim(arr1)

2

In [9]:
np.shape(arr1)

(3, 4)

In [10]:
arr2 =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [11]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr2[ 0,0:4]

array([1, 2, 3, 4])

In [20]:
arr2[2][3]

12

In [30]:
np.extract(arr2%2 !=0,arr2)

array([ 1,  3,  5,  7,  9, 11])

               Or 

In [29]:
odd_elements = arr2[arr2 % 2 == 1]

print(f"Odd-indexed elements: {odd_elements}")

Odd-indexed elements: [ 1  3  5  7  9 11]


Ans :-

In [49]:
Random_matrix = np.random.random((3,3))

In [50]:
Random_matrix

array([[0.87560018, 0.89342016, 0.30520091],
       [0.73711871, 0.44649629, 0.20155574],
       [0.2406117 , 0.06084186, 0.16639821]])

In [55]:
np.random.rand(2,2)

array([[0.51441006, 0.65381058],
       [0.48713444, 0.68732894]])

while np.random.randn creates an array of the given shape and populate it with random samples from a normal distribution with a specific mean and standard deviation.

Exp:-

In [60]:
np.random.randn(2,2)

array([[-1.76942914, -0.66798011],
       [-0.37386673,  1.21665565]])

In [61]:
arr3=np.expand_dims(arr1, axis = 1)

In [62]:
arr3

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [63]:
arr4=np.expand_dims(arr1, axis = 0)

In [64]:
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [67]:
arr5=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [68]:
arr5.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [71]:
Arr6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Arr7 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [72]:
Arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
Arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
Arr6*Arr7

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [75]:
Arr6@Arr7

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [76]:
Arr6@Arr7.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [77]:
Arr6+Arr7

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [78]:
Arr6-Arr7

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
Arr6/Arr7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
Arr8 = np.array([1,2,3], dtype =  np.int16)

In [90]:
print(Arr8.byteswap(True))

[256 512 768]


In [91]:
Arr9 = np.diag([1,3,4])

In [92]:
Arr9

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [93]:
np.linalg.inv(Arr9)

array([[1.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.25      ]])

In [94]:
Arr10 = np.array([[1,2],[3,4]])

In [96]:
Arr10

array([[1, 2],
       [3, 4]])

In [95]:
Arr10.reshape(1,4)

array([[1, 2, 3, 4]])

In [97]:
Arr10.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [99]:
Arr11 = np.zeros((3,3))

In [100]:
Arr11

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [101]:
Arr11 +5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])