In [61]:
import numpy as np
data=np.array([[1],[2],[3]])

In [62]:
data.ndim

2

In [63]:
data

array([[1],
       [2],
       [3]])

In [64]:
a=np.squeeze(data)

In [65]:
a.ndim

1

Repeat

In [66]:
a

array([1, 2, 3])

In [67]:
data

array([[1],
       [2],
       [3]])

In [68]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [69]:
a=np.array([[1,2],[3,4]])

In [70]:
b=np.repeat(a,2)

In [71]:
b.reshape(2,4)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [72]:
b

array([1, 1, 2, 2, 3, 3, 4, 4])

In [73]:
a

array([[1, 2],
       [3, 4]])

In [74]:
np.repeat(a,2,axis =1 )

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [75]:
np.repeat(a,2,axis =0 )

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [ ]:
np.roll()

It is rolling orrotating the data 

In [77]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [78]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [79]:
np.roll(data, 3)

array([[1],
       [2],
       [3]])

In [80]:
np.roll(data, 4)

array([[3],
       [1],
       [2]])

In [81]:
b = np.diag(np.array([1,2,3,4]))

In [82]:
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [83]:
np.roll(b, 1)

array([[4, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [84]:
a= np.array([[[1,2],[3,4],[5,6]]])

In [85]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [86]:
np.roll(a, 1, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [87]:
np.roll(a, 1, axis = 1)

array([[[5, 6],
        [1, 2],
        [3, 4]]])

In [88]:
np.roll(a, 1, axis = 2)

array([[[2, 1],
        [4, 3],
        [6, 5]]])

In [89]:
np.roll(a, 1, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
axis=0  it will repeat row wise and axis =1 it will roll column wise 

In [92]:
arr1 =np.random.randint(1,10,(3,4)) 

In [93]:
arr2 =np.random.randint(1,10,(3,4)) 

In [94]:
arr1

array([[8, 5, 6, 1],
       [4, 6, 8, 6],
       [9, 6, 2, 8]])

In [95]:
arr2

array([[7, 5, 8, 7],
       [3, 1, 2, 4],
       [7, 5, 9, 4]])

In [96]:
arr1+arr2

array([[15, 10, 14,  8],
       [ 7,  7, 10, 10],
       [16, 11, 11, 12]])

In [ ]:
It gives u indexwise summition

In [100]:
arr1*arr2

array([[56, 25, 48,  7],
       [12,  6, 16, 24],
       [63, 30, 18, 32]])

In [101]:
arr1/arr2

array([[1.14285714, 1.        , 0.75      , 0.14285714],
       [1.33333333, 6.        , 4.        , 1.5       ],
       [1.28571429, 1.2       , 0.22222222, 2.        ]])

In [102]:
arr1-arr2

array([[ 1,  0, -2, -6],
       [ 1,  5,  6,  2],
       [ 2,  1, -7,  4]])

In [103]:
arr1**arr2

array([[2097152,    3125, 1679616,       1],
       [     64,       6,      64,    1296],
       [4782969,    7776,     512,    4096]])

arr1

In [104]:
arr2

array([[7, 5, 8, 7],
       [3, 1, 2, 4],
       [7, 5, 9, 4]])

In [105]:
arr1 > arr2

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [106]:
~arr1

array([[ -9,  -6,  -7,  -2],
       [ -5,  -7,  -9,  -7],
       [-10,  -7,  -3,  -9]])

Bitwise negation 

Numpy string function

In [107]:
arr= np.array(["pw","Skills"])

In [108]:
arr

array(['pw', 'Skills'], dtype='<U6')

In [109]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [110]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [111]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [112]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [114]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
Mathematical Function 

In [115]:
arr1

array([[8, 5, 6, 1],
       [4, 6, 8, 6],
       [9, 6, 2, 8]])

In [116]:
np.sin(arr1)

array([[ 0.98935825, -0.95892427, -0.2794155 ,  0.84147098],
       [-0.7568025 , -0.2794155 ,  0.98935825, -0.2794155 ],
       [ 0.41211849, -0.2794155 ,  0.90929743,  0.98935825]])

In [117]:
np.cos(arr1)

array([[-0.14550003,  0.28366219,  0.96017029,  0.54030231],
       [-0.65364362,  0.96017029, -0.14550003,  0.96017029],
       [-0.91113026,  0.96017029, -0.41614684, -0.14550003]])

In [118]:
np.log10(arr1)

array([[0.90308999, 0.69897   , 0.77815125, 0.        ],
       [0.60205999, 0.77815125, 0.90308999, 0.77815125],
       [0.95424251, 0.77815125, 0.30103   , 0.90308999]])

In [119]:
np.power(arr1,2)

array([[64, 25, 36,  1],
       [16, 36, 64, 36],
       [81, 36,  4, 64]])

In [120]:
np.mean(arr1)

5.75

In [121]:
np.max(arr1)

9

In [122]:
np.std(arr1)

2.3496453633119474

In [123]:
np.max(arr1)

9

In [124]:
arr1-arr2

array([[ 1,  0, -2, -6],
       [ 1,  5,  6,  2],
       [ 2,  1, -7,  4]])

In [126]:
np.subtract(arr1,arr2)

array([[ 1,  0, -2, -6],
       [ 1,  5,  6,  2],
       [ 2,  1, -7,  4]])

In [127]:
arr1*arr2

array([[56, 25, 48,  7],
       [12,  6, 16, 24],
       [63, 30, 18, 32]])

In [128]:
np.multiply(arr1,arr2)

array([[56, 25, 48,  7],
       [12,  6, 16, 24],
       [63, 30, 18, 32]])

In [129]:
np.mod(arr1,arr2)

array([[1, 0, 6, 1],
       [1, 0, 0, 2],
       [2, 1, 2, 0]])

In [130]:
np.power(arr1, arr2)

array([[2097152,    3125, 1679616,       1],
       [     64,       6,      64,    1296],
       [4782969,    7776,     512,    4096]])

In [131]:
np.var(arr1)

5.520833333333333

Sorting and searching in the array

In [132]:
arr =np.array([5,6,1,2])

In [133]:
arr

array([5, 6, 1, 2])

In [134]:
np.sort(arr)

array([1, 2, 5, 6])

In [137]:
np.searchsorted(arr,3)

4

Insert that at 3rd place in order to get original array into sorted format

In [138]:
arr1 =np.array([0,1,2,3,0,4])

In [140]:
np.count_nonzero(arr1)

4

In [141]:
np.where(arr1>0)

(array([1, 2, 3, 5]),)

In [143]:
np.extract(arr1>0,arr1)

array([1, 2, 3, 4])

In [151]:
arr3 =np.array([5,6,100,200,1,2,8,9])

In [152]:
np.searchsorted(arr3,7)

6

In [157]:
arr3

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [158]:
np.sort(arr3)

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [159]:
np.searchsorted(arr3,3)

6

We will see it latr 

In [160]:
arr3 >0

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [161]:
np.where(arr3>0)

(array([0, 1, 2, 3, 4, 5, 6, 7]),)

In [162]:
np.extract(arr3>0,arr3)

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [163]:
arr1

array([0, 1, 2, 3, 0, 4])

In [165]:
arr3.byteswap()

array([  360287970189639680,   432345564227567616,  7205759403792793600,
       -4035225266123964416,    72057594037927936,   144115188075855872,
         576460752303423488,   648518346341351424])

Matrix is a 2-d array  

In [166]:
import numpy.matlib as nm

In [167]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [168]:
nm.ones((4,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Numpy linear algebra

In [170]:
arr4 =np.random.randint(1,10,(3,4)) 

In [171]:
arr5 =np.random.randint(1,10,(3,4)) 

In [175]:
arr4 = np.array([[2,3],[4,5]])

In [178]:
arr5 = np.array([[1,3],[4,5]])

In [181]:
arr4

array([[2, 3],
       [4, 5]])

In [179]:
arr5

array([[1, 3],
       [4, 5]])

In [180]:
arr4@arr5

array([[14, 21],
       [24, 37]])

**How to solve linear equations using Numpy ??

In [184]:
b = np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [185]:
b

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [186]:
c = np.array ([16,-8,0])

In [187]:
np.linalg.solve(b,c)

array([1., 3., 2.])

Inverse of a matrix ??

In [189]:
arr4

array([[2, 3],
       [4, 5]])

In [190]:
np.linalg.det(arr4)

-2.0

In [192]:
np.linalg.inv(arr4)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [ ]:
............................................................Numpy ends................................................................................