EXTRA TOPICS 

In [2]:
arr = np.one(3,4)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [6]:
arr = np.ones((3,4))

In [7]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [15]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((3,3))

array([[4.68617808e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [35]:
np.empty((3,4),dtype =int)

array([[4635963235168681984, 4635963235168681984, 4635963235168681984,
        4635963235168681984],
       [4635963235168681984, 4635963235168681984, 4635963235168681984,
        4635963235168681984],
       [4635963235168681984, 4635963235168681984, 4635963235168681984,
        4635963235168681984]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(3,dtype =int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
np.eye(1,dtype =int)

array([[1]])

There is a concept of dataframe.

Optional Topic

In [38]:
import pandas as pd

In [39]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

To calculate inverse of a matrix we use np.eye()

Extra Topic:Random is a library 

In [59]:
import random


In [48]:
random.choice((1,2,3,4,5,6))

6

In [58]:
random.choice(("Ajay"))

'a'

In [57]:
random.random()

0.2294691437437758

A RANDOM NO IS GENERATED BETWEEN 0 AND 1 O INCLUDED AND 1 EXCLUDED

In [60]:
random.randrange(1,1000)

407

In [63]:
random.randrange(1,1000)

106

In [64]:
random.randrange(1,1000)

319

In [67]:
random.uniform(7,14)     

10.611190228852514

 no between 7 and 14 having same probability

In [71]:
lis = [1,2,3,4,5,6,7,8]
random.shuffle(lis)

In [72]:
lis

[5, 7, 8, 6, 2, 3, 1, 4]

In [73]:
random.choice("pooja")

'p'

In [74]:
import numpy as np
np.random.rand(2,3)

array([[0.35142701, 0.26913082, 0.10623921],
       [0.83373255, 0.3114602 , 0.0564987 ]])

In [75]:
np.random.rand(1)

array([0.35643334])

In [13]:
np.random.randn(2,3)

array([[-0.19445926,  0.39050727,  0.12037729],
       [-0.07373561,  0.09765784, -1.13339751]])

In [78]:
np.rand(2)

AttributeError: module 'numpy' has no attribute 'rand'

In [79]:
np.random.random_sample()

0.7308055836385372

Return random  number exclude 0 and iclude 1 

In [80]:
np.random.randint(1,5, size = (3,4))

array([[1, 3, 3, 1],
       [3, 3, 1, 4],
       [1, 4, 1, 1]])

In [81]:
arr = np.random.randint(1,5,size=(3,4))

In [82]:
arr

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [83]:
arr.size

12

In [84]:
arr.shape

(3, 4)

In [85]:
arr.ndim

2

  Array size cannot change

Reshaping Array but size does't change

In [86]:
arr.reshape(2,6)

array([[2, 4, 3, 2, 4, 1],
       [2, 4, 4, 3, 3, 3]])

In [28]:
arr.reshape(6,2)

array([[2, 2],
       [1, 3],
       [2, 1],
       [3, 4],
       [4, 1],
       [3, 3]])

In [87]:
arr.reshape(2,1)

ValueError: cannot reshape array of size 12 into shape (2,1)

In [88]:
arr.reshape(12,)

array([2, 4, 3, 2, 4, 1, 2, 4, 4, 3, 3, 3])

In [89]:
arr.reshape(12,1)

array([[2],
       [4],
       [3],
       [2],
       [4],
       [1],
       [2],
       [4],
       [4],
       [3],
       [3],
       [3]])

In [31]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [90]:
arr.reshape(3,4)

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [91]:
arr.reshape(4,3)

array([[2, 4, 3],
       [2, 4, 1],
       [2, 4, 4],
       [3, 3, 3]])

In [92]:
arr.reshape(-1,4)

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [95]:
arr.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [93]:
arr.reshape(3,-100)

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [96]:
arr.reshape(-1,5)

ValueError: cannot reshape array of size 12 into shape (5)

In [94]:
arr.reshape(3,4).base

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

What is happening is it creating a deep copy or shallow copyreshape function 

In [97]:
arr.reshape(3,4).base

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

It wiil be a shallow copy 

In [98]:
arr.reshape(3,4).base

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [102]:
arr.reshape(12,).base

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

If i will do .base actually it will show base array

In [103]:
arr.reshape(12,).base

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

How can i reshape into some other dimension ?

In [104]:
arr.size

12

In [105]:
arr.reshape(2,2,3)

array([[[2, 4, 3],
        [2, 4, 1]],

       [[2, 4, 4],
        [3, 3, 3]]])

In [106]:
arr.reshape(1,2,2,3)

array([[[[2, 4, 3],
         [2, 4, 1]],

        [[2, 4, 4],
         [3, 3, 3]]]])

In [107]:
arr.reshape(4,3,1)

array([[[2],
        [4],
        [3]],

       [[2],
        [4],
        [1]],

       [[2],
        [4],
        [4]],

       [[3],
        [3],
        [3]]])

In [108]:
arr.reshape(1,1,1,1,1,1,1,1,1,1,2,2,3)

array([[[[[[[[[[[[[2, 4, 3],
                  [2, 4, 1]],

                 [[2, 4, 4],
                  [3, 3, 3]]]]]]]]]]]]])

In [109]:
lis=[1,2,3]

In [110]:
np.array(lis)

array([1, 2, 3])

In [111]:
arr

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [112]:
arr.ndim

2

In [117]:
arr2=np.array([[2,3],[4,5]])
arr2

array([[2, 3],
       [4, 5]])

In [118]:
arr2.ndim

2

In [119]:
arr2 =np.zeros((3,4))

In [120]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
arr2.ndim

2

In [122]:
arr3 =np.zeros((1,3,4))

In [123]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

3rows,4 columns =>2-d arrays +1-dim

In [124]:
arr3.ndim

3

In [125]:
arr4 = np.zeros((1,2,3,3))

In [126]:
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [127]:
arr4.ndim

4

In [128]:
arr4.shape

(1, 2, 3, 3)

In [129]:
arr3=np.zeros((1,3,4))

In [130]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [131]:
arr3.ndim

3

In [132]:
arr3.shape

(1, 3, 4)

In [133]:
arr3=np.zeros((2,3,4))

In [134]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [135]:
arr3=np.zeros((3,3,4))

In [136]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [141]:
arr3=np.ones((3,3,4))

In [142]:
arr3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [143]:
arr3.shape

(3, 3, 4)

In [157]:
arr1 = np.random.randint(1,10,(5,6))

In [158]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [159]:
arr1>5

array([[False,  True,  True,  True, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [ True, False,  True, False,  True,  True]])

In [160]:
arr1[arr1>5]

array([6, 9, 9, 7, 6, 7, 8, 9, 8, 7])

In [162]:
arr1[arr1<5]

array([4, 4, 1, 2, 4, 2, 3, 2, 4, 3, 1, 3, 1, 4, 2, 4, 1])

In [163]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [166]:
arr

array([[2, 4, 3, 2],
       [4, 1, 2, 4],
       [4, 3, 3, 3]])

In [165]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [167]:
arr[0]

array([2, 4, 3, 2])

In [171]:
arr1[0][5]

1

In [172]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [173]:
arr1[0]

array([4, 6, 9, 9, 4, 1])

In [174]:
arr1[0][0]

4

In [194]:
arr1[0 , 1:3]

array([6, 9])

In [195]:
arr1[0 , [1:3]]

SyntaxError: invalid syntax (2527413691.py, line 1)

In [202]:
arr[2,4,[2,3]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [203]:
arr[2:4,[2,3]]

array([[3, 3]])

In [204]:
arr1[2]

array([6, 4, 3, 5, 7, 1])

In [205]:
arr1[2:4]

array([[6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4]])

In [206]:
arr1[2:4,[0,2]]

array([[6, 3],
       [3, 1]])

In [207]:
arr1[[2,4],0:2]

array([[6, 4],
       [8, 5]])

In [208]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [209]:
arr1[0]

array([4, 6, 9, 9, 4, 1])

In [210]:
arr1[2]

array([6, 4, 3, 5, 7, 1])

In [211]:
arr1[2:5]

array([[6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [212]:
arr1[2:5,[0,2]]

array([[6, 3],
       [3, 1],
       [8, 9]])

In [213]:
arr1[2:5, 0:2]

array([[6, 4],
       [3, 5],
       [8, 5]])

Slicing of the array

In [214]:
arr1[2:4]

array([[6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4]])

In [215]:
arr1[2,4]

7

In [216]:
arr1[2:5,[0,2]]

array([[6, 3],
       [3, 1],
       [8, 9]])

In [217]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [221]:
arr1[[2,4],[0,2]]

array([6, 9])

In [223]:
arr1[[2,4]]

array([[6, 4, 3, 5, 7, 1],
       [8, 5, 9, 1, 8, 7]])

In [224]:
arr1

array([[4, 6, 9, 9, 4, 1],
       [7, 2, 4, 2, 3, 2],
       [6, 4, 3, 5, 7, 1],
       [3, 5, 1, 4, 2, 4],
       [8, 5, 9, 1, 8, 7]])

In [225]:
arr1[2]

array([6, 4, 3, 5, 7, 1])

In [227]:
arr1[[2,4]]

array([[6, 4, 3, 5, 7, 1],
       [8, 5, 9, 1, 8, 7]])

Selecting specific columns

In [229]:
arr[2:4]

array([[4, 3, 3, 3]])

Slicing

In [233]:
arr[2:4 ,[1,3]]

array([[3, 3]])

In [236]:
arr1= np.random.randint(1,3,(3,3))
arr2= np.random.randint(1,3,(3,3))

In [235]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [237]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [239]:
arr1+arr2

array([[2, 2, 2],
       [4, 2, 4],
       [4, 2, 4]])

In [240]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [241]:
arr1*arr2

array([[1, 1, 1],
       [4, 1, 4],
       [4, 1, 4]])

Matrix Multiplication:

In [242]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [243]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [244]:
arr1@arr2

array([[5, 3, 5],
       [8, 5, 8],
       [8, 5, 8]])

In [245]:
5/0

ZeroDivisionError: division by zero

In [247]:
arr1 / 0

/tmp/ipykernel_237/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

Broadcasting 

In [250]:
arr = np.zeros((3,4))

In [251]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Broadcasting simply means u are doing something with each and every element of the array.

In [252]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [253]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [256]:
a = np.array([1,2,3,4])

In [257]:
a

array([1, 2, 3, 4])

In [258]:
a+arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [259]:
arr[1]+a

array([1., 2., 3., 4.])

In [260]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [261]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [273]:
a=np.array([[1,2,3]])

In [274]:
a

array([[1, 2, 3]])

In [275]:
arr+a

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

Transpose :

In [276]:
a.T

array([[1],
       [2],
       [3]])

In [277]:
arr.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [278]:
a.T

array([[1],
       [2],
       [3]])

In [279]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [280]:
a

array([[1, 2, 3]])

In [281]:
a.T

array([[1],
       [2],
       [3]])

In [282]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [283]:
a = np.array([1,2,3])

In [284]:
a

array([1, 2, 3])

In [285]:
a.T

array([1, 2, 3])

In [286]:
a = np.array([[1,2,3]])

In [287]:
a

array([[1, 2, 3]])

In [288]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [289]:
np.log10(arr1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

In [290]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [291]:
np.min(a)

1

In [292]:
a

array([[1, 2, 3]])

In [293]:
np.min(a)

1

In [294]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [295]:
np.min(arr1)

1

In [296]:
np.max(arr1)

2

In [297]:
arr1.T

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [299]:
arr1.flatten()

array([1, 1, 1, 2, 1, 2, 2, 1, 2])

Reduce higher dimension tolower dimension

Expand dimension: This expands the array by inserting a new axis(dimension) i.e. increase dimension. We have already reshape then why expand?

Usecase:A lot in  Image processing

axis=0 row-wise and axis=1 column-wise

In [304]:
arr = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [305]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [306]:
np.sum(arr)

27

In [307]:
np.sum(arr,axis = 0)

array([ 6,  9, 12])

Row wise added though it seems Column wise sum but summision is row-wise.

In [309]:
np.sum(arr,axis = 1)

array([ 6, 15,  6])

Column wise added though it seems row wise sum but summision is column-wise.

Expand Dimension of array


In [311]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [312]:
arr.ndim

1

In [315]:
arr1=np.expand_dims(arr, axis = 0)

In [316]:
arr1

array([[1, 2, 3, 4]])

In [317]:
arr1.ndim

2

In [320]:
arr2=np.expand_dims(arr1, axis = 0)

In [321]:
arr2

array([[[1, 2, 3, 4]]])

In [322]:
arr2.shape

(1, 1, 4)

In [323]:
arr

array([1, 2, 3, 4])

In [324]:
arr1=np.expand_dims(arr, axis = 1)

In [325]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [326]:
arr1.ndim

2

In [327]:
arr = np.zeros((3,4))

In [328]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [329]:
arr1=np.expand_dims(arr, axis = 0)

In [330]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [331]:
arr1=np.expand_dims(arr, axis = 1)

In [332]:
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

Numpy will not have that much application but pandas have too much  applications. 