In [ ]:
ML TOOLBOX 
    |
____|_____________________________________________
|       |          |         |          |         |
Numpy  Pandas  Seaborn   Mathplotlib  Statistics MLOps

 Functions are some python program which can be reused.

Library:-Collection of function so that it can be reusable and optimised.

Nump:- Numerical Python  used in data analysis

In [4]:
import numpy as np

Matlab,Tora ,Lingo these were softwares for mathematical computations.

Numpy was created in  2005 by Travis Oilphant at Bell Laboratory 

Numpy is built on C/C++ because C++ is developted as the fastest programming languague.
Why? Numpy ?
Numpy is fast due to one of it's basic component that is array.

How to see any library version ?

In [8]:
np.__version__

'1.23.5'

In [10]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

Why Numpy ?

Around 10,000 mathematical function in numpy and it is faster as compare to other data structure as it uses array.

In [17]:
l=[1,2,3,4,5]

In [18]:
np.array(l)

array([1, 2, 3, 4, 5])

In [19]:
type(np.array(l))

numpy.ndarray

What does this mean?

ndarray means n-dimensional array.

What is array?

Array is the way  in which numpy stores the only the same type of data i.e. homogenious data.

Why numpy faster than list ?

In [20]:
type(np.array(l))

numpy.ndarray

In [24]:
arr=np.array(l)

In [25]:
arr.ndim

1

In [32]:
l=[1,2,3,4,5,"Rishi"]
arr1 = np.array(l) 
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U21')

What is this arr.ndim ?

In [34]:
arr1=np.array([[1,2,3],[4,5,6]])

In [35]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr1.ndim

2

In [39]:
l1=[1,2,3,4]

In [42]:
matrix1 = np.matrix(l)

In [43]:
matrix1 

matrix([[1, 2, 3, 4]])

In [44]:
l=[1,2,3,4,5,"Rishi"]

In [46]:
matrix2 = np.matrix(l)

In [47]:
matrix2

matrix([['1', '2', '3', '4', '5', 'Rishi']], dtype='<U21')

In [48]:
matrix2.ndim

2

Matrix is bydefault 2-dimension.

In [55]:
np.matrix([[1,2],
            [3,4],
            [5,6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

more way to convert to array 

In [ ]:
np.asarray([[1,2],
            [3,4],
            [5,6]])

In [58]:
np.asanyarray([[1,2],
            [3,4],
            [5,6]])
#Convert the input to an ndarray, but pass ndarray subclasses through.


array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
matrix1

matrix([[1, 2, 3, 4]])

In [61]:
np.asanyarray(matrix1)

matrix([[1, 2, 3, 4]])

Not converted to the array it is still the matrix.

Means it will convert anything into an array but if it is already a subclass of an array it will simply pass through it that is difference between numpy.asanyarray and numpy.asarray

In [62]:
np.array([[1,2],
            [3,4],
            [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
t= ([1,2,3],[4,5,6])
type(t)

tuple

In [64]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a=5 
np.array(a)

array(5)

In [66]:
l=[1,2,3,4,5]
array3 = np.array(l)

In [69]:
a=array3

In [70]:
a

array([1, 2, 3, 4, 5])

In [71]:
array3[0]=1000

In [72]:
array3

array([1000,    2,    3,    4,    5])

In [74]:
a

array([1000,    2,    3,    4,    5])

Cheating Example

Whenever change in one araay chac=nge gets in other array then it is shallow copy .

In [75]:
b=a.copy()
b[0]=2000

In [76]:
b

array([2000,    2,    3,    4,    5])

In deep copy it  will re-allocate to a new memory location so change in b will not reflect in other.

To create array we have 3 functions 

Functions inside numpy to generate array

In [77]:
#1.
np.fromfunction(lambda i,j :i==j, shape =(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [78]:
np.fromfunction(lambda i,j :i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [79]:
arr.shape

(5,)

In [80]:
arr1.shape

(2, 3)

2 rows and 3 coloumns are there. 

In [82]:
arr.size

5

In [83]:
arr1.size

6

In [85]:
np.fromfunction(lambda i,j :i*j, (3,3)) 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [86]:
range(0,5)

range(0, 5)

It is an iterator 

In [87]:
for i in range(5):
    print(i)

0
1
2
3
4


In [89]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [90]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [92]:
( i*i for i in range(5))

<generator object <genexpr> at 0x7f552f0c0eb0>

In [93]:
iterable= ( i*i for i in range(5))

In [104]:
np.fromiter(iterable, int )

array([], dtype=int64)

In [99]:
np.fromstring('23 34 56', sep =' ')

array([23., 34., 56.])

Separator is the value which is used to separate the value.

In [100]:
np.fromstring('Suhani,Ajay,ANMESHA', sep =' ')

/tmp/ipykernel_135/194877578.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,ANMESHA', sep =' ')


array([], dtype=float64)

In [105]:
arr

array([1, 2, 3, 4, 5])

In [106]:
arr.shape

(5,)

In [107]:
arr.size

5

In [108]:
arr.dtype

dtype('int64')

In [110]:
l=[1,2,3]
arr=np.array(l)
arr.dtype

dtype('int64')

In [111]:
arr

array([1, 2, 3])

In [117]:
list(range(1,5))

[1, 2, 3, 4]

In [118]:
range(5)

range(0, 5)

In [ ]:
What is difference and second thing can i use decimal

In [119]:
list(range(1.0,5.0))

TypeError: 'float' object cannot be interpreted as an integer

In [120]:
range(5.0)

TypeError: 'float' object cannot be interpreted as an integer

In [122]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [123]:
list(np.arange(0.1,10.2,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001]

In [125]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

np.linspace gives at equidistance vaues

In [126]:
np.linspace(1,5,200)

array([1.        , 1.0201005 , 1.04020101, 1.06030151, 1.08040201,
       1.10050251, 1.12060302, 1.14070352, 1.16080402, 1.18090452,
       1.20100503, 1.22110553, 1.24120603, 1.26130653, 1.28140704,
       1.30150754, 1.32160804, 1.34170854, 1.36180905, 1.38190955,
       1.40201005, 1.42211055, 1.44221106, 1.46231156, 1.48241206,
       1.50251256, 1.52261307, 1.54271357, 1.56281407, 1.58291457,
       1.60301508, 1.62311558, 1.64321608, 1.66331658, 1.68341709,
       1.70351759, 1.72361809, 1.74371859, 1.7638191 , 1.7839196 ,
       1.8040201 , 1.8241206 , 1.84422111, 1.86432161, 1.88442211,
       1.90452261, 1.92462312, 1.94472362, 1.96482412, 1.98492462,
       2.00502513, 2.02512563, 2.04522613, 2.06532663, 2.08542714,
       2.10552764, 2.12562814, 2.14572864, 2.16582915, 2.18592965,
       2.20603015, 2.22613065, 2.24623116, 2.26633166, 2.28643216,
       2.30653266, 2.32663317, 2.34673367, 2.36683417, 2.38693467,
       2.40703518, 2.42713568, 2.44723618, 2.46733668, 2.48743

In [131]:
np.logspace(1,5,10,base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [132]:
np.logspace(1,5,10,base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr1 = np.zeros(5)

In [10]:
arr2 = np.zeros((3,4))

In [11]:
arr2.ndim

2

In [12]:
arr3 = np.zeros((3,3,4))

In [13]:
arr3.shape

(3, 3, 4)

In [14]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

arr3 = np.zeros((3,3,4))
meaning is repeat 3*4 matrix 3 times

first 3 is repeatition of times second is 3 column and 4 is rows

In [16]:
arr4 = np.zeros((4,3,4))

In [17]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.one(5)

AttributeError: module 'numpy' has no attribute 'one'

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
arr4 = np.zeros((4,3,3,4))

In [21]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arr = np.ones((3,4))

In [26]:
arr +5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [27]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

Why u use 0 and 1 ?
Used in image processing and etc. 

In [28]:
np.array([[[[[[[[[[[[[1,1,1,1,1,]]]]]]]]]]]]])

array([[[[[[[[[[[[[1, 1, 1, 1, 1]]]]]]]]]]]]])

In [29]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [30]:
l = [1, 2,3, 4,5, "Prince"]
arr = np.array(l)
arr.dtype

dtype('<U21')

In [31]:
arr

array(['1', '2', '3', '4', '5', 'Prince'], dtype='<U21')

Question : Why numpy?

In [32]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot for matrix multiplication
matrix_product = np.dot(A, B)
print("Matrix product using np.dot:\n", matrix_product)

# Using @ operator for matrix multiplication (Python 3.5 and later)
matrix_product = A @ B
print("Matrix product using @ operator:\n", matrix_product)

Matrix product using np.dot:
 [[19 22]
 [43 50]]
Matrix product using @ operator:
 [[19 22]
 [43 50]]


In [33]:
import numpy as np
import time

# Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

# Print the time taken for the vectorized version
print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

# Reset result_vectorized to 0
result_vectorized = 0

# Measure time for the version using a for loop
start_time_for_loop = time.time()
for index in range(1000000):
    result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

# Print the time taken for the for loop version
print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")


Time taken for vectorized calculation: 22.307157516479492 milliseconds
Time taken for calculation using a for loop: 755.281925201416 milliseconds


In [34]:
np.array(np.matrix([[1, 2], [5, 6]]))

array([[1, 2],
       [5, 6]])

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [36]:
np.count_nonzero(arr)

6

In [37]:
import numpy as geek 
  
my_scalar = 12
   
print ("Input  scalar : ", my_scalar) 
    
out_arr = geek.asanyarray(my_scalar)  
print ("output array from input scalar : ", out_arr)  
print(type(out_arr)) 

Input  scalar :  12
output array from input scalar :  12
<class 'numpy.ndarray'>
